DROP TABLE IF EXISTS AuthenticationService;

CREATE TABLE IF NOT EXISTS login_users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);